// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB6J4adIn5NfVWaYdFcu0fvpLS67NG3KMo',
    appId: '1:837325732700:web:80ff5be927c69478001f99',
    messagingSenderId: '837325732700',
    projectId: 'attend-sys-b7472',
    authDomain: 'attend-sys-b7472.firebaseapp.com',
    storageBucket: 'attend-sys-b7472.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBHm812x50pHv4AqxjoPvPR2ZVU3tumphQ',
    appId: '1:837325732700:android:3ca8b15c6e2907ae001f99',
    messagingSenderId: '837325732700',
    projectId: 'attend-sys-b7472',
    storageBucket: 'attend-sys-b7472.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD06VvIUyzhfcpeiXVowkYtH8TVHyXCc-E',
    appId: '1:837325732700:ios:c40e2119ada7ecce001f99',
    messagingSenderId: '837325732700',
    projectId: 'attend-sys-b7472',
    storageBucket: 'attend-sys-b7472.firebasestorage.app',
    iosBundleId: 'com.example.attendSys',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD06VvIUyzhfcpeiXVowkYtH8TVHyXCc-E',
    appId: '1:837325732700:ios:c40e2119ada7ecce001f99',
    messagingSenderId: '837325732700',
    projectId: 'attend-sys-b7472',
    storageBucket: 'attend-sys-b7472.firebasestorage.app',
    iosBundleId: 'com.example.attendSys',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB6J4adIn5NfVWaYdFcu0fvpLS67NG3KMo',
    appId: '1:837325732700:web:a0d673c15eec1f7e001f99',
    messagingSenderId: '837325732700',
    projectId: 'attend-sys-b7472',
    authDomain: 'attend-sys-b7472.firebaseapp.com',
    storageBucket: 'attend-sys-b7472.firebasestorage.app',
  );
}
